package com.hr.hr.Entity.Enum;

public enum Department_Name {
    FINANCE,
    MARKETING,
    SALES,
    INFORMATION_TECHNOLOGY,
    CUSTOMER_SUPPORT,
    RESEARCH_AND_DEVELOPMENT,
    ADMINISTRATION,
    TRAINING_AND_DEVELOPMENT
}
